source:      .
destination: ./site
layouts:     ./templates

include:      ["build"]
exclude:      ["templates", "assets"]

# Site settings
title:
email:
description:
baseurl: ""
url: "http://yourdomain.com"
permalink: ":title"

# Build settings
markdown: kramdown
