source:      .
destination: ./site
layouts:     ./templates

include:      []
exclude:      ["templates", "assets"]

# Site settings
title: 
email: 
description: 
baseurl: "/Personnal/romain-portfolio/site/"
url: "http://yourdomain.com"
permalink: ":title"

# Build settings
markdown: kramdown
